### ISSUE TITLE
VCMixer build error

### ISSUE THREAD

**Issue by davephillips** [VCVRack/Fundamental#36]
Linux Fedora 23
Rack master (git pull 13 March)

g++ -Wsuggest-override -std=c++11 -fPIC -I../../include -I../../dep/include -DSLUG=Fundamental -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/VCMixer.cpp.o src/VCMixer.cpp
src/VCMixer.cpp: In constructor ‘VCMixerWidget::VCMixerWidget(VCMixer*)’:
src/VCMixer.cpp:50:32: error: ‘LEDSliderGreen’ was not declared in this scope
   addParam(ParamWidget::create<LEDSliderGreen>(mm2px(Vec(5.8993969, 44.33149).plus(Vec(-2, 0))), module, VCMixer::LVL_PARAM + 0, 0.0, 1.0, 1.0));
                                ^
src/VCMixer.cpp:50:143: error: no matching function for call to ‘rack::Parameter::create(rack::Vec, VCMixer*&, int, double, double, double)’
   addParam(ParamWidget::create<LEDSliderGreen>(mm2px(Vec(5.8993969, 44.33149).plus(Vec(-2, 0))), module, VCMixer::LVL_PARAM + 0, 0.0, 1.0, 1.0));
                                                                                                                                               ^
In file included from ../../include/rack.hpp:9:0,
                 from src/Fundamental.hpp:1,
                 from src/VCMixer.cpp:1:
../../include/app.hpp:244:12: note: candidate: template<class T> static T* rack::Parameter::create(rack::Vec, rack::Module*, int, float, float, float)
  static T *create(Vec pos, Module *module, int paramId, float minValue, float maxValue, float defaultValue) {
            ^
../../include/app.hpp:244:12: note:   template argument deduction/substitution failed:
src/VCMixer.cpp:50:143: error: template argument 1 is invalid
   addParam(ParamWidget::create<LEDSliderGreen>(mm2px(Vec(5.8993969, 44.33149).plus(Vec(-2, 0))), module, VCMixer::LVL_PARAM + 0, 0.0, 1.0, 1.0));
                                                                                                                                               ^
src/VCMixer.cpp:51:32: error: the value of ‘LEDSliderGreen’ is not usable in a constant expression
   addParam(ParamWidget::create<LEDSliderGreen>(mm2px(Vec(17.899343, 44.331486).plus(Vec(-2, 0))), module, VCMixer::LVL_PARAM + 1, 0.0, 1.0, 1.0));
                                ^
src/VCMixer.cpp:50:32: note: ‘LEDSliderGreen’ was not declared ‘constexpr’
   addParam(ParamWidget::create<LEDSliderGreen>(mm2px(Vec(5.8993969, 44.33149).plus(Vec(-2, 0))), module, VCMixer::LVL_PARAM + 0, 0.0, 1.0, 1.0));
                                ^
src/VCMixer.cpp:51:144: error: no matching function for call to ‘rack::Parameter::create(rack::Vec, VCMixer*&, int, double, double, double)’
   addParam(ParamWidget::create<LEDSliderGreen>(mm2px(Vec(17.899343, 44.331486).plus(Vec(-2, 0))), module, VCMixer::LVL_PARAM + 1, 0.0, 1.0, 1.0));
                                                                                                                                                ^
In file included from ../../include/rack.hpp:9:0,
                 from src/Fundamental.hpp:1,
                 from src/VCMixer.cpp:1:
../../include/app.hpp:244:12: note: candidate: template<class T> static T* rack::Parameter::create(rack::Vec, rack::Module*, int, float, float, float)
  static T *create(Vec pos, Module *module, int paramId, float minValue, float maxValue, float defaultValue) {
            ^
../../include/app.hpp:244:12: note:   template argument deduction/substitution failed:
src/VCMixer.cpp:52:32: error: the value of ‘LEDSliderGreen’ is not usable in a constant expression
   addParam(ParamWidget::create<LEDSliderGreen>(mm2px(Vec(29.899292, 44.331486).plus(Vec(-2, 0))), module, VCMixer::LVL_PARAM + 2, 0.0, 1.0, 1.0));
                                ^
src/VCMixer.cpp:50:32: note: ‘LEDSliderGreen’ was not declared ‘constexpr’
   addParam(ParamWidget::create<LEDSliderGreen>(mm2px(Vec(5.8993969, 44.33149).plus(Vec(-2, 0))), module, VCMixer::LVL_PARAM + 0, 0.0, 1.0, 1.0));
                                ^
src/VCMixer.cpp:52:144: error: no matching function for call to ‘rack::Parameter::create(rack::Vec, VCMixer*&, int, double, double, double)’
   addParam(ParamWidget::create<LEDSliderGreen>(mm2px(Vec(29.899292, 44.331486).plus(Vec(-2, 0))), module, VCMixer::LVL_PARAM + 2, 0.0, 1.0, 1.0));
                                                                                                                                                ^
In file included from ../../include/rack.hpp:9:0,
                 from src/Fundamental.hpp:1,
                 from src/VCMixer.cpp:1:
../../include/app.hpp:244:12: note: candidate: template<class T> static T* rack::Parameter::create(rack::Vec, rack::Module*, int, float, float, float)
  static T *create(Vec pos, Module *module, int paramId, float minValue, float maxValue, float defaultValue) {
            ^
../../include/app.hpp:244:12: note:   template argument deduction/substitution failed:
src/VCMixer.cpp:53:32: error: the value of ‘LEDSliderGreen’ is not usable in a constant expression
   addParam(ParamWidget::create<LEDSliderGreen>(mm2px(Vec(41.90065, 44.331486).plus(Vec(-2, 0))), module, VCMixer::LVL_PARAM + 3, 0.0, 1.0, 1.0));
                                ^
src/VCMixer.cpp:50:32: note: ‘LEDSliderGreen’ was not declared ‘constexpr’
   addParam(ParamWidget::create<LEDSliderGreen>(mm2px(Vec(5.8993969, 44.33149).plus(Vec(-2, 0))), module, VCMixer::LVL_PARAM + 0, 0.0, 1.0, 1.0));
                                ^
src/VCMixer.cpp:53:143: error: no matching function for call to ‘rack::Parameter::create(rack::Vec, VCMixer*&, int, double, double, double)’
   addParam(ParamWidget::create<LEDSliderGreen>(mm2px(Vec(41.90065, 44.331486).plus(Vec(-2, 0))), module, VCMixer::LVL_PARAM + 3, 0.0, 1.0, 1.0));
                                                                                                                                               ^
In file included from ../../include/rack.hpp:9:0,
                 from src/Fundamental.hpp:1,
                 from src/VCMixer.cpp:1:
../../include/app.hpp:244:12: note: candidate: template<class T> static T* rack::Parameter::create(rack::Vec, rack::Module*, int, float, float, float)
  static T *create(Vec pos, Module *module, int paramId, float minValue, float maxValue, float defaultValue) {
            ^
../../include/app.hpp:244:12: note:   template argument deduction/substitution failed:
../../compile.mk:57: recipe for target 'build/src/VCMixer.cpp.o' failed
make: *** [build/src/VCMixer.cpp.o] Error 1

**Comment by AndrewBelt** [comment]
Fixed

**Comment by davephillips** [comment]
Hi Andrew, I'm still getting that error after a fresh pull. Did you push the fix ?

**Comment by davephillips** [comment]
Never mind, I missed that the fix was in Rack, not in Fundamental. Updating now, sorry for the noise.
